[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[features]
alloc = []
std = []

# enable log support
log = ["dep:log"]
# enable defmt support
defmt = ["dep:defmt"]

[dependencies]
log = { version = "0.4", optional = true }
defmt = {version = "1.0.1", optional = true }
